declare module '@loaders.gl/loader-utils' {
  export type DataType = any;
  export type SyncDataType = any;
  export type BatchableDataType = any;
  export type TransformBatches = any;
  export type TypedArray = any;
  export type BigTypedArray = any;
  export type TypedArrayConstructor = any;
  export type BigTypedArrayConstructor = any;
  export type NumberArray = any;
  export type NumericArray = any;
  export type FetchLike = any;
  export type Format = any;
  export type Loader = any;
  export type LoaderWithParser = any;
  export type LoaderContext = any;
  export type StrictLoaderOptions = any;
  export type LoaderOptions = any;
  export type LoaderOptionsType = any;
  export type LoaderReturnType = any;
  export type LoaderBatchType = any;
  export type LoaderArrayOptionsType = any;
  export type LoaderArrayReturnType = any;
  export type LoaderArrayBatchType = any;
  export type Writer = any;
  export type WriterWithEncoder = any;
  export type WriterOptions = any;
  export type WriterOptionsType = any;
  export type WriterDataType = any;
  export type WriterBatchType = any;
  export type ReadableStreamType = any;
  export type RequiredOptions = any;
  export type ReadableFile = any;
  export type WritableFile = any;
  export type Stat = any;
  export type FileSystem = any;
  export type RandomAccessFileSystem = any;
  export type Source = any;
  export type SourceArrayOptionsType = any;
  export type SourceArrayDataSourceType = any;
  export type DataSourceOptions = any;
  export type ImageType = any;
  export type ImageSourceMetadata = any;
  export type GetImageParameters = any;
  export type VectorSource = any;
  export type VectorSourceMetadata = any;
  export type GetFeaturesParameters = any;
  export type TileSource = any;
  export type TileSourceMetadata = any;
  export type GetTileParameters = any;
  export type GetTileDataParameters = any;
  export type ImageTileSource = any;
  export type VectorTileSource = any;
  export type VectorTile = any;

  export const parseFromContext: any;
  export const parseSyncFromContext: any;
  export const parseInBatchesFromContext: any;
  export const assert: any;
  export const isBrowser: any;
  export const isWorker: any;
  export const nodeVersion: any;
  export const self: any;
  export const window: any;
  export const global: any;
  export const document: any;
  export const log: any;
  export const isObject: any;
  export const isPureObject: any;
  export const isArrayBuffer: any;
  export const isArrayBufferLike: any;
  export const isPromise: any;
  export const isIterable: any;
  export const isAsyncIterable: any;
  export const isIterator: any;
  export const isResponse: any;
  export const isFile: any;
  export const isBlob: any;
  export const isWritableDOMStream: any;
  export const isReadableDOMStream: any;
  export const isWritableNodeStream: any;
  export const isReadableNodeStream: any;
  export const isReadableStream: any;
  export const isWritableStream: any;
  export const mergeOptions: any;
  export const getRequiredOptions: any;
  export const registerJSModules: any;
  export const checkJSModule: any;
  export const getJSModule: any;
  export const getJSModuleOrNull: any;
  export const createLoaderWorker: any;
  export const parseWithWorker: any;
  export const canParseWithWorker: any;
  export const canEncodeWithWorker: any;
  export const parseJSON: any;
  export const sliceArrayBuffer: any;
  export const concatenateArrayBuffers: any;
  export const concatenateArrayBuffersFromArray: any;
  export const concatenateTypedArrays: any;
  export const compareArrayBuffers: any;
  export const padToNBytes: any;
  export const copyToArray: any;
  export const copyArrayBuffer: any;
  export const padStringToByteAlignment: any;
  export const copyStringToDataView: any;
  export const copyBinaryToDataView: any;
  export const copyPaddedArrayBufferToDataView: any;
  export const copyPaddedStringToDataView: any;
  export const getFirstCharacters: any;
  export const getMagicString: any;
  export const makeTextEncoderIterator: any;
  export const makeTextDecoderIterator: any;
  export const makeLineIterator: any;
  export const makeNumberedLineIterator: any;
  export const forEach: any;
  export const concatenateArrayBuffersAsync: any;
  export const toArrayBufferIterator: any;
  export const RequestScheduler: any;
  export const setPathPrefix: any;
  export const getPathPrefix: any;
  export const resolvePath: any;
  export const _addAliases: any;
  export const JSONLoader: any;
  export const isBuffer: any;
  export const toBuffer: any;
  export const toArrayBuffer: any;
  export const toArrayBufferView: any;
  export const copyToArrayBuffer: any;
  export const ensureArrayBuffer: any;
  export const promisify1: any;
  export const promisify2: any;
  export const path: any;
  export const stream: any;
  export const BlobFile: any;
  export const HttpFile: any;
  export const NodeFile: any;
  export const NodeFilesystem: any;
  export const DataSource: any;
  export const ImageSource: any;
}
